apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: public_ips
      protocol: layer2
      addresses:
      - 192.168.50.150-192.168.60.250
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   namespace: metallb-system
#   name: config
# data:
#   config: |
#     peers:
#     - my-asn: 65000
#       peer-asn: 65102
#       peer-address: 192.168.50.251
#     address-pools:
#     - name: public_ips
#       protocol: bgp
#       addresses:
#       - 192.168.60.150-192.168.60.250